# Generated by Django 5.2.6 on 2025-09-18 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contatos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endereco",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "logradouro",
                    models.CharField(help_text="Entre o logradouro", max_length=200),
                ),
                ("numero", models.CharField(help_text="Entre o número", max_length=10)),
                (
                    "complemento",
                    models.CharField(
                        blank=True, help_text="Entre o complemento", max_length=50
                    ),
                ),
                (
                    "bairro",
                    models.CharField(help_text="Entre o bairro", max_length=100),
                ),
                (
                    "cidade",
                    models.CharField(help_text="Entre a cidade", max_length=100),
                ),
                ("estado", models.CharField(help_text="Entre o estado", max_length=2)),
                ("cep", models.CharField(help_text="Entre o CEP", max_length=10)),
                (
                    "pessoa",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enderecos",
                        to="contatos.pessoa",
                    ),
                ),
            ],
        ),
    ]
